### ISSUE TITLE
feat(device): add xiaomi aqara water sensor

### ISSUE THREAD

**Issue by szappanyos** [Neonox31/zigate#8]
@Neonox31 if you could give me some basic info about how to start, then I will try to implement this feature. Thanks

**Comment by Neonox31** [comment]
Hello @szappanyos 

First you need to analyse zigate frames of your device, for that you can add the following nodes to your node-red instance : 
```
[{"id":"d6fc3890.3aac18","type":"zigate-in","z":"e984d6b5.9bd7d8","name":"","zigate":"66f7be03.29302","x":143,"y":169,"wires":[["bb478428.ccc2d8"]]},{"id":"bb478428.ccc2d8","type":"debug","z":"e984d6b5.9bd7d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":316,"y":169,"wires":[]},{"id":"66f7be03.29302","type":"zigate-config","z":"","serialPort":"/dev/ttyUSB0"}]
```
and start node-red using the following command `DEBUG='zigate*' node-red` for seeing transmitted zigate frames. Reverse engineering is the most difficult part...

For adding a new device in the code, modifications are principaly lcoated into the `device.ts` file and in the `devices/xiaomi` folder in your case. You could take an existing device as example.
This zigate library uses observables for broadcasting messages to devices. Each device exposes one observable per function (i.e: temperature$ for weather-sensor).

Feel free to start your device integration in a dedicated pull request and I will help you 😉
